# -*- coding: utf-8 -*-
"""projeto 26/05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEyC1IG3yacsHOv4dqZrxJV1E1Udx0Z2
"""

import sqlite3

LIMITE_ESTOQUE_BAIXO = 5


def conectar():
    return sqlite3.connect("estoque.db")

def inicializar_banco():
    with conectar() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS produtos (
                id        INTEGER PRIMARY KEY AUTOINCREMENT,
                nome      TEXT    NOT NULL UNIQUE,
                categoria TEXT    NOT NULL,
                preco     REAL    NOT NULL,
                quantidade INTEGER NOT NULL
            )
        """)


def cadastrar_produto(nome, categoria, preco, quantidade):
    try:
        with conectar() as conn:
            conn.execute(
                "INSERT INTO produtos (nome, categoria, preco, quantidade) VALUES (?, ?, ?, ?)",
                (nome, categoria, preco, quantidade)
            )
        print("\nProduto cadastrado com sucesso!\n")
    except sqlite3.IntegrityError:
        print(f"\nProduto '{nome}' já existe no estoque.\n")

def atualizar_estoque(item, quantidade):
    with conectar() as conn:
        cur = conn.execute(
            "UPDATE produtos SET quantidade = quantidade + ? WHERE LOWER(nome) = LOWER(?)",
            (quantidade, item)
        )
        if cur.rowcount:
            print(f"{quantidade} unidade(s) adicionada(s) de '{item}'.")
        else:
            print("Item não encontrado no estoque.")

def retirar_item(item, quantidade):
    with conectar() as conn:
        cur = conn.execute(
            "SELECT quantidade FROM produtos WHERE LOWER(nome) = LOWER(?)", (item,)
        )
        row = cur.fetchone()
        if not row:
            print("Item não encontrado no estoque.")
            return
        if row[0] < quantidade:
            print("Estoque insuficiente.")
            return
        conn.execute(
            "UPDATE produtos SET quantidade = quantidade - ? WHERE LOWER(nome) = LOWER(?)",
            (quantidade, item)
        )
        print(f"{quantidade} unidade(s) retirada(s) de '{item}'.")

def listar_produtos():
    with conectar() as conn:
        return conn.execute(
            "SELECT nome, categoria, preco, quantidade FROM produtos ORDER BY nome"
        ).fetchall()


def exibir_estoque():
    produtos = listar_produtos()
    if not produtos:
        print("\n Nenhum item cadastrado no estoque.\n")
        return

    print("\n=== ESTOQUE ===")
    alertas = []

    for nome, categoria, preco, quantidade in produtos:
        print(f"""
  Nome:       {nome}
  Categoria:  {categoria}
  Preço:      R$ {preco:.2f}
  Quantidade: {quantidade}
  ------------------------""")
        if quantidade <= LIMITE_ESTOQUE_BAIXO:
            alertas.append((nome, quantidade))

    if alertas:
        print("\nALERTAS DE ESTOQUE BAIXO:")
        for nome, qtd in alertas:
            print(f"   • {nome}: apenas {qtd} unidade(s) restante(s)!")
    print()


def main():
    inicializar_banco()

    while True:
        print(f"{'='*12} ERP (Gestão de Estoque) {'='*12}\n")
        print("1 - Cadastrar Produto")
        print("2 - Atualizar quantidade")
        print("3 - Consultar estoque")
        print("4 - Sair")

        try:
            opcao = int(input("\nDigite a opção desejada: "))
        except ValueError:
            print("\nErro: digite um número de 1 a 4!\n")
            continue

        if opcao not in range(1, 5):
            print("\nErro: opção inválida!\n")
            continue

        if opcao == 1:
            print(f"\n{'='*7} Cadastrar novo produto {'='*7}")
            nome      = input("Nome do produto:      ")
            categoria = input("Categoria:            ")
            try:
                preco     = float(input("Preço (R$):           "))
                quantidade = int(input("Quantidade inicial:   "))
            except ValueError:
                print("\nValor inválido. Tente novamente.\n")
                continue
            cadastrar_produto(nome, categoria, preco, quantidade)

        elif opcao == 2:
            item = input("\nNome do item: ")
            print("1 - Adicionar\n2 - Retirar")
            op = input("Escolha o número da operação: ")

            try:
                quantidade = int(input("Quantidade: "))
            except ValueError:
                print("\nQuantidade inválida.\n")
                continue

            if op == "1":
                atualizar_estoque(item, quantidade)
            elif op == "2":
                retirar_item(item, quantidade)
            else:
                print("Opção inválida.")

            exibir_estoque()

        elif opcao == 3:
            exibir_estoque()

        elif opcao == 4:
            print("\n Saindo do programa... Até logo!\n")
            break

if __name__ == "__main__":
    main()