# -*- coding: utf-8 -*-
"""projeto 26/05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEyC1IG3yacsHOv4dqZrxJV1E1Udx0Z2
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile inicializar_banco.py
# import sqlite3
# 
# def conectar():
#     return sqlite3.connect("estoque.db")
# 
# 
# def inicializar_banco():
#     with conectar() as conn:
#         conn.execute("""
#             CREATE TABLE IF NOT EXISTS produtos (
#                 id INTEGER PRIMARY KEY AUTOINCREMENT,
#                 nome TEXT NOT NULL UNIQUE,
#                 categoria TEXT NOT NULL,
#                 preco REAL NOT NULL,
#                 quantidade INTEGER NOT NULL
#             )
#         """)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile estoque.py
# from banco import conectar
# 
# LIMITE_ESTOQUE_BAIXO = 5
# 
# 
# def cadastrar_produto(nome, categoria, preco, quantidade):
#     try:
#         with conectar() as conn:
#             conn.execute(
#                 """
#                 INSERT INTO produtos
#                 (nome, categoria, preco, quantidade)
#                 VALUES (?, ?, ?, ?)
#                 """,
#                 (nome, categoria, preco, quantidade)
#             )
#         print("\nProduto cadastrado com sucesso!\n")
# 
#     except:
#         print(f"\nProduto '{nome}' já existe.\n")
# 
# 
# def atualizar_estoque(item, quantidade):
#     with conectar() as conn:
# 
#         cur = conn.execute(
#             """
#             UPDATE produtos
#             SET quantidade = quantidade + ?
#             WHERE LOWER(nome) = LOWER(?)
#             """,
#             (quantidade, item)
#         )
# 
#         if cur.rowcount:
#             print(f"{quantidade} unidade(s) adicionada(s).")
#         else:
#             print("Produto não encontrado.")
# 
# 
# def retirar_item(item, quantidade):
# 
#     with conectar() as conn:
# 
#         cur = conn.execute(
#             """
#             SELECT quantidade
#             FROM produtos
#             WHERE LOWER(nome) = LOWER(?)
#             """,
#             (item,)
#         )
# 
#         row = cur.fetchone()
# 
#         if not row:
#             print("Produto não encontrado.")
#             return
# 
#         if row[0] < quantidade:
#             print("Estoque insuficiente.")
#             return
# 
#         conn.execute(
#             """
#             UPDATE produtos
#             SET quantidade = quantidade - ?
#             WHERE LOWER(nome) = LOWER(?)
#             """,
#             (quantidade, item)
#         )
# 
#         print(f"{quantidade} unidade(s) retirada(s).")
# 
# 
# def listar_produtos():
# 
#     with conectar() as conn:
# 
#         return conn.execute(
#             """
#             SELECT nome, categoria, preco, quantidade
#             FROM produtos
#             ORDER BY nome
#             """
#         ).fetchall()
# 
# 
# def exibir_estoque():
# 
#     produtos = listar_produtos()
# 
#     if not produtos:
#         print("\nNenhum produto cadastrado.\n")
#         return
# 
#     print("\n===== ESTOQUE =====")
# 
#     alertas = []
# 
#     for nome, categoria, preco, quantidade in produtos:
# 
#         print(f"""
# Nome: {nome}
# Categoria: {categoria}
# Preço: R$ {preco:.2f}
# Quantidade: {quantidade}
# ------------------------
# """)
# 
#         if quantidade <= LIMITE_ESTOQUE_BAIXO:
#             alertas.append((nome, quantidade))
# 
#     if alertas:
# 
#         print("\nALERTAS DE ESTOQUE BAIXO:")
# 
#         for nome, qtd in alertas:
#             print(f"{nome}: apenas {qtd} unidade(s)")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile interface.py
# from estoque import (
#     cadastrar_produto,
#     atualizar_estoque,
#     retirar_item,
#     exibir_estoque
# )
# 
# 
# def menu():
# 
#     while True:
# 
#         print("\n===== ERP ESTOQUE =====\n")
# 
#         print("1 - Cadastrar Produto")
#         print("2 - Atualizar Estoque")
#         print("3 - Consultar Estoque")
#         print("4 - Sair")
# 
#         try:
#             opcao = int(input("\nEscolha uma opção: "))
# 
#         except ValueError:
#             print("Digite apenas números.")
#             continue
# 
#         if opcao == 1:
# 
#             nome = input("Nome: ")
#             categoria = input("Categoria: ")
# 
#             try:
#                 preco = float(input("Preço: "))
#                 quantidade = int(input("Quantidade: "))
# 
#             except ValueError:
#                 print("Valor inválido.")
#                 continue
# 
#             cadastrar_produto(
#                 nome,
#                 categoria,
#                 preco,
#                 quantidade
#             )
# 
#         elif opcao == 2:
# 
#             item = input("Nome do produto: ")
# 
#             print("1 - Adicionar")
#             print("2 - Retirar")
# 
#             op = input("Escolha: ")
# 
#             try:
#                 quantidade = int(input("Quantidade: "))
# 
#             except ValueError:
#                 print("Quantidade inválida.")
#                 continue
# 
#             if op == "1":
#                 atualizar_estoque(item, quantidade)
# 
#             elif op == "2":
#                 retirar_item(item, quantidade)
# 
#             else:
#                 print("Opção inválida.")
# 
#             exibir_estoque()
# 
#         elif opcao == 3:
#             exibir_estoque()
# 
#         elif opcao == 4:
#             print("Encerrando sistema...")
#             break
# 
#         else:
#             print("Opção inválida.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from banco import inicializar_banco
# from interface import menu
# 
# 
# def main():
# 
#     inicializar_banco()
# 
#     menu()
# 
# 
# if __name__ == "__main__":
#     main()

from google.colab import drive
drive.mount('/content/drive')